#!/bin/sh

sxhkd &
remaps &
$HOME/.config/polybar/launch.sh &
xrdb -merge $HOME/.Xresources
xsetroot -cursor_name left_ptr &

# For Java windows (Matlab)
wmname LG3D


monitors=$(xrandr --listactivemonitors | sed "/Monitor/ d" | awk '{print $4}' | tr '\n' ':')
num=$(expr $(xrandr --listactivemonitors | wc -l) - 1)

if [ "$num" = 1 ]; then
	mainmonitor=$(echo $monitors | tr ':' '\n')
	bspc monitor $mainmonitor -d 1 2 3 4 5
elif [ -n $(echo $monitors | grep 'DP2-3') ]; then
	mainmonitor='eDP1'
	secondmonitor='DP2-3'
	bspc monitor $mainmonitor -d 1 2 3 4 5
	bspc monitor $secondmonitor -d 6 7 8 9 0
else
	mainmonitor='DP2-3'
	secondmonitor='eDP1'
	bspc monitor $mainmonitor -d 1 2 3 4 5
	bspc monitor $secondmonitor -d 6 7 8 9 0
fi


bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  \#181818
bspc config focused_border_color \#00BFFF
# bspc config urgent_border_color  \#000000
# bspc config presel_border_color  \#000000
bspc config pointer_modifier mod4

# Remove unplugged monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Set monocle by default
for n in $(seq 1 5); do
    bspc desktop $n --layout monocle
done
