#!/bin/sh

# POSIX compliant version of tabs

# First argument = focused color
# Second argument = unfocused color

# WLIST=$(bspc query -N -n .window -d focused | tr '\n' ' ')
# FWIN=$(bspc query -N -n .window.focused)
DESKTOP=$(wmctrl -d | grep '*' | awk '{print $1}')
FOCUSID=$(bspc query -N -n .window.focused | tr '[:upper:]' '[:lower:]')
WLIST=$(wmctrl -l | grep "  $DESKTOP" | awk {'first = $1; $1=""; $2=""; $3=""; print $0'} | sed 's/^   //g' | sed -E 's/(.{30})(.{1,})$/\1.../' | tr '\n' ' ')
FWIN=$(wmctrl -l | grep "$FOCUSID" | awk {'first = $1; $1=""; $2=""; $3=""; print $0'} | sed 's/^   //g')
# printf '%s  ' "$WLIST"

for NAME in $WLIST; do
	# TITLE=$(wmctrl -l | grep "$ID" | awk '{print $4}' | sed -E 's/(.{30})(.{1,})$/\1.../')
	if [ "$NAME" = "$FWIN" ]; then
		TABS="$TABS%{A1:bspc node -f $ID:}%{F$1}$NAME%{F- O18 A}"
	else
		TABS="$TABS%{A1:bspc node -f $ID:}%{F$2}$NAME%{F- O18 A}"
	fi
done

echo "$TABS"
