#!/bin/sh

# First argument = focused color
# Second argument = unfocused color

TABS=''
WLIST=$(bspc query -N -n .window -d focused | tr '\n' ' ')
FWIN=$(bspc query -N -n .window.focused | tr '[:upper:]' '[:lower:]')

for ID in $WLIST; do
    TITLE=$(wmctrl -l | grep $ID | awk {'first = $1; $1=""; $2=""; $3=""; print $0'} | sed 's/^   //g' | sed -E 's/(.{30})(.{1,})$/\1.../')
    if [ "$ID" = "$FWIN" ]; then
	    TABS="$TABS%{A1:bspc node -f $ID:}%{F$1}$TITLE%{F- O18 A}"
    else
	    TABS="$TABS%{A1:bspc node -f $ID:}%{F$2}$TITLE%{F- O18 A}"
    fi
done

echo $TABS
